version: '3.8'

services:
  spring-app:
    image: inheecho/business-test2  # Spring Boot 애플리케이션 이미지
#    build:
    ##      context: .
    ##      dockerfile: Dockerfile
    container_name: spring-container
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - spring-net
    volumes:
      - /home/ec2-user/logs:/logs

  redis-app:
    image: redis:latest
    container_name: redis-container
    depends_on:
      - spring-app
    ports:
      - "6379:6379"
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
volumes:
  logs:
